
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 29 09:48:59 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 43;
  public static final int PLUSPLUS = 33;
  public static final int CHAR = 48;
  public static final int CONST = 21;
  public static final int NAMESPACE = 12;
  public static final int GREATER = 40;
  public static final int LPAREN = 10;
  public static final int SEMI = 8;
  public static final int CONTINUE = 30;
  public static final int LESS = 39;
  public static final int FOR = 37;
  public static final int MINUS = 3;
  public static final int STATIC = 38;
  public static final int RPAREN = 13;
  public static final int AND = 35;
  public static final int OR = 34;
  public static final int BOOL = 45;
  public static final int ELESS = 41;
  public static final int COMMA = 9;
  public static final int CLASS = 23;
  public static final int DIV = 5;
  public static final int DOUBLEDOT = 19;
  public static final int DIFFERENT = 44;
  public static final int PLUS = 2;
  public static final int IF = 49;
  public static final int LSQBRACE = 14;
  public static final int THIS = 22;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 32;
  public static final int RETURN = 25;
  public static final int EQUAL = 7;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int NUMBER = 46;
  public static final int EGREATER = 42;
  public static final int MOD = 6;
  public static final int IDENT = 47;
  public static final int BREAK = 29;
  public static final int VOID = 26;
  public static final int ARROW = 18;
  public static final int ELSE = 50;
  public static final int LBRACE = 16;
  public static final int READ = 31;
  public static final int FINAL = 27;
  public static final int RBRACE = 17;
  public static final int EXTENDS = 20;
  public static final int PROG = 11;
  public static final int RSQBRACE = 15;
  public static final int PRINT = 24;
}

